# Generated by Django 6.0.3 on 2026-04-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('profesional', 'Profesional'), ('usuario', 'Usuario')], max_length=20),
        ),
    ]
