# Generated by Django 6.0.3 on 2026-05-04 03:52

from django.db import migrations, models


def crear_servicios_iniciales(apps, schema_editor):
    Servicio = apps.get_model('core', 'Servicio')
    servicios = [
        ('corte', 'Corte de pelo', 'Cortes personalizados segun tu estilo y tipo de cabello.', 'imagenes/cortepelo.png'),
        ('alisado', 'Alisado', 'Alisado profesional para un acabado suave y de larga duracion.', 'imagenes/alisado.png'),
        ('botox', 'Botox capilar', 'Tratamiento reparador que revitaliza y reduce el frizz.', 'imagenes/botox.png'),
        ('peinado', 'Peinado', 'Peinados profesionales para cualquier ocasion y estilo.', 'imagenes/peinado.png'),
        ('keratina', 'Tratamiento de keratina', 'Fortalece la fibra capilar y mejora la textura del cabello.', 'imagenes/keratina.png'),
        ('coloracion', 'Coloracion', 'Tecnicas de color modernas para un resultado luminoso y natural.', 'imagenes/coloracion.png'),
    ]

    for orden, (codigo, nombre, descripcion, imagen) in enumerate(servicios, start=1):
        Servicio.objects.get_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'descripcion': descripcion,
                'imagen': imagen,
                'activo': True,
                'orden': orden,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cuidadorecomendacion_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RunPython(crear_servicios_iniciales, migrations.RunPython.noop),
    ]
