# Generated by Django 6.0.3 on 2026-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_archivo',
            field=models.FileField(blank=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
