# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicio_imagen_archivo_servicio_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
